### ISSUE TITLE
[1.10.2] Server crash on load

### ISSUE THREAD

**Issue by C0rn3j** [Bottersnike/StepAssistMod#1]
I realize this is not a server mod but let the mod be in the server mods folder,  in my case I symlinked the mods with client and server and this is the only mod that crashes.

partial crashlog: http://pastebin.com/q0jdSmvh
 
Forge:2088

If you need the full crash log let me know.

**Comment by Bottersnike** [comment]
Okay. Thanks. I forgot to only load client side parts on the client. I'm fixing that now and I'll have a new version out shortly.

**Comment by Bottersnike** [comment]
Give the latest version (0.1.4) a try. I think I've fixed it.

**Comment by C0rn3j** [comment]
Server works, can't test if client does. Thanks

**Comment by Bottersnike** [comment]
Closing
